# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayesRSamplerV2 <- function(outputFile, seed, max_iterations, burn_in, thinning, X, Y, sigma0, v0E, s02E, v0G, s02G, cva) {
    invisible(.Call(`_BayesRRcpp_BayesRSamplerV2`, outputFile, seed, max_iterations, burn_in, thinning, X, Y, sigma0, v0E, s02E, v0G, s02G, cva))
}

BayesRSamplerV2Groups <- function(outputFile, seed, max_iterations, burn_in, thinning, X, Y, sigma0, v0E, s02E, v0G, s02G, cva, groups, gAssign) {
    invisible(.Call(`_BayesRRcpp_BayesRSamplerV2Groups`, outputFile, seed, max_iterations, burn_in, thinning, X, Y, sigma0, v0E, s02E, v0G, s02G, cva, groups, gAssign))
}

BRV2Grstart <- function(outputFile, seed, max_iterations, burn_in, thinning, mu, beta, sigmaE, sigmaGG, X, epsilon, components, sigma0, v0E, s02E, v0G, s02G, cva, groups, gAssign) {
    invisible(.Call(`_BayesRRcpp_BRV2Grstart`, outputFile, seed, max_iterations, burn_in, thinning, mu, beta, sigmaE, sigmaGG, X, epsilon, components, sigma0, v0E, s02E, v0G, s02G, cva, groups, gAssign))
}

dirichilet_rng <- function(alpha) {
    .Call(`_BayesRRcpp_dirichilet_rng`, alpha)
}

inv_gamma_rng <- function(shape, scale) {
    .Call(`_BayesRRcpp_inv_gamma_rng`, shape, scale)
}

gamma_rng <- function(shape, scale) {
    .Call(`_BayesRRcpp_gamma_rng`, shape, scale)
}

inv_gamma_rate_rng <- function(shape, rate) {
    .Call(`_BayesRRcpp_inv_gamma_rate_rng`, shape, rate)
}

gamma_rate_rng <- function(shape, rate) {
    .Call(`_BayesRRcpp_gamma_rate_rng`, shape, rate)
}

inv_scaled_chisq_rng <- function(dof, scale) {
    .Call(`_BayesRRcpp_inv_scaled_chisq_rng`, dof, scale)
}

norm_rng <- function(mean, sigma2) {
    .Call(`_BayesRRcpp_norm_rng`, mean, sigma2)
}

component_probs <- function(b2, pi) {
    .Call(`_BayesRRcpp_component_probs`, b2, pi)
}

