# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sumDiagonal <- function(Ma, va) {
    .Call(`_BayesRRcpp_sumDiagonal`, Ma, va)
}

mvn_rng <- function(nn, mean, covar) {
    .Call(`_BayesRRcpp_mvn_rng`, nn, mean, covar)
}

mvnCoef_rng <- function(nn, xty, xtx, d) {
    .Call(`_BayesRRcpp_mvnCoef_rng`, nn, xty, xtx, d)
}

mvnCoef_rngAug <- function(nn, y, x, d) {
    .Call(`_BayesRRcpp_mvnCoef_rngAug`, nn, y, x, d)
}

RandomG <- function(shape, scale) {
    .Call(`_BayesRRcpp_RandomG`, shape, scale)
}

