# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BayesRSamplerV2 <- function(outputFile, seed, max_iterations, burn_in, thinning, X, Y, sigma0, v0E, s02E, v0G, s02G, B) {
    invisible(.Call(`_BayesRRcpp_BayesRSamplerV2`, outputFile, seed, max_iterations, burn_in, thinning, X, Y, sigma0, v0E, s02E, v0G, s02G, B))
}

dirichilet_rng <- function(alpha) {
    .Call(`_BayesRRcpp_dirichilet_rng`, alpha)
}

inv_gamma_rng <- function(shape, scale) {
    .Call(`_BayesRRcpp_inv_gamma_rng`, shape, scale)
}

gamma_rng <- function(shape, scale) {
    .Call(`_BayesRRcpp_gamma_rng`, shape, scale)
}

inv_gamma_rate_rng <- function(shape, rate) {
    .Call(`_BayesRRcpp_inv_gamma_rate_rng`, shape, rate)
}

gamma_rate_rng <- function(shape, rate) {
    .Call(`_BayesRRcpp_gamma_rate_rng`, shape, rate)
}

inv_scaled_chisq_rng <- function(dof, scale) {
    .Call(`_BayesRRcpp_inv_scaled_chisq_rng`, dof, scale)
}

norm_rng <- function(mean, sigma2) {
    .Call(`_BayesRRcpp_norm_rng`, mean, sigma2)
}

component_probs <- function(b2, pi) {
    .Call(`_BayesRRcpp_component_probs`, b2, pi)
}

HorseshoeP <- function(outputFile, seed, max_iterations, burn_in, thinning, X, Y, A, v0E, s02E, vL, vT, B) {
    invisible(.Call(`_BayesRRcpp_HorseshoeP`, outputFile, seed, max_iterations, burn_in, thinning, X, Y, A, v0E, s02E, vL, vT, B))
}

HorseshoePlus <- function(outputFile, seed, max_iterations, burn_in, thinning, X, Y, A, v0E, s02E, vL, vT, B) {
    invisible(.Call(`_BayesRRcpp_HorseshoePlus`, outputFile, seed, max_iterations, burn_in, thinning, X, Y, A, v0E, s02E, vL, vT, B))
}

sumDiagonal <- function(Ma, va) {
    .Call(`_BayesRRcpp_sumDiagonal`, Ma, va)
}

mvn_rng <- function(nn, mean, covar) {
    .Call(`_BayesRRcpp_mvn_rng`, nn, mean, covar)
}

mvnCoef_rng <- function(nn, xty, xtx, d, sigma) {
    .Call(`_BayesRRcpp_mvnCoef_rng`, nn, xty, xtx, d, sigma)
}

RHorseshoeP <- function(outputFile, seed, max_iterations, burn_in, thinning, X, Y, A, v0E, s02E, vL, vT, B, vC, sC) {
    invisible(.Call(`_BayesRRcpp_RHorseshoeP`, outputFile, seed, max_iterations, burn_in, thinning, X, Y, A, v0E, s02E, vL, vT, B, vC, sC))
}

